### ISSUE TITLE
Multiple keybinds for one command

### ISSUE THREAD

**Issue by toylatte** [ayntgl/discordo#100]
How do I make it so I can do either keystroke A or keystroke B for a certain command in `discordo.toml`?

**Comment by ayntgl** [comment]
Currently, this is not possible, since each keybinding action/command accepts a string value. Any specific reason as to why you may want to have multiple shortcut for an action?

**Comment by toylatte** [comment]
Thx for the quick reply.

I just think this would be convenient for me when I am focusing the messages view because visually it could be either alt up arrow or alt right arrow depending on which pane is focused.
