### ISSUE TITLE
panic: HTTP 400 Bad Request, {"captcha_key": ["captcha-required"]

### ISSUE THREAD

**Issue by nopalfi** [ayntgl/discordo#106]
So, i tried to install it on my Arch Linux, it returned that error...
It seems that it requires to bypass the captcha security to log in into a account.
Or did i miss some configuration or something?
This also failed when i try to use my bot token, it returned the same error.
Any idea how to fix this?

**Comment by ayntgl** [comment]
https://github.com/ayntgl/discordo/issues/86#issuecomment-954091787
