### ISSUE TITLE
Feature Request: Support Bot Tokens

### ISSUE THREAD

**Issue by OpenSrcerer** [ayntgl/discordo#115]
### Why Add this Feature
As a long-term Discord user, I would love to use this client, but I wouldn't want to put any of my accounts at risk. Thus, I believe that adding support for bot tokens is a good suggestion.

### Current Behavior
When using a bot token with the `DISCORDO_TOKEN` environment variable, UI fails to start.

### Error Dump
```
panic: websocket: close 4013: Invalid intent(s).

goroutine 1 [running]:
main.main()
	/path/to/installation/discordo/main.go:24 +0x25a
```

### Notes
I have checked that my bot's privileged intents are enabled (on the discord developers website).

**Comment by ayntgl** [comment]
Support for bot accounts has been added in the latest commit. To login with a bot account, assign the `DISCORDO_TOKEN` environment variable to the token of the bot with "Bot " as the prefix (eg: `Bot OzI2MpC5NrQxNsE2Nzc5nDx2.Yc2KlA.2iz-5JxgxG-9Yb8GHzBwn-NJjfg`).
