### ISSUE TITLE
Unable to login to Discordo

### ISSUE THREAD

**Issue by ODellKyle** [ayntgl/discordo#126]
Issue: Unable to login to Discordo, appears to be failing captcha request. I suspect this is a result of the latest 0.17 update from Discord?

I do not think it is successfully hitting the discordgo login endpoint, which may be as of result of pacman not having the latest version of Discord yet.

Steps to reproduce:
1. Enter 'discordo' into command line and hit enter
2. Enter correct email and password
3. Click Login

Expected Result: Successfully logs into discord, lands on chat screens
Actual Result: Discordo closes, user is returned to command line

![image](https://user-images.githubusercontent.com/48389758/154611505-56a6ee7d-9f3e-4fd3-8b0a-34bf9eb23383.png)

**Comment by ayntgl** [comment]
You can either resolve this issue by:
1. logging into Discord using web browser and solving the captcha.
2. using the authentication token and assigning it to the `DISCORDO_TOKEN` environment variable.

**Comment by ayntgl** [comment]
You can easily retrieve client authentication token using https://github.com/diamondburned/discordlogin

**Comment by ODellKyle** [comment]
It took me a minute, but I figured it out. Thanks @ayntgl !!
