### ISSUE TITLE
captcha error

### ISSUE THREAD

**Issue by ElecTwix** [ayntgl/discordo#132]
# captcha error

## What I tired.

- I tired to wait for 12h it didn't work also.
- 
- Open in Web discord and solve captcha 2 times for skip

## Error Output

`panic: HTTP 400 Bad Request, {"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", "captcha_service": "hcaptcha"} [recovered]
	panic: HTTP 400 Bad Request, {"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", "captcha_service": "hcaptcha"}
`

**Comment by ayntgl** [comment]
#86
