### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Firemonk21** [ayntgl/discordo#150]
When logging in I am not able to make it past the "login" button with correct information. I can get it to error when entering incorrect passwords or emails, but with the correct information it just hangs for a second before moving me back to the email message area.

running the windows prebuilt binary.

**Comment by twokilohertz** [comment]
Just built the latest version from the GitHub repository on Linux and tried to login as well and got similar behaviour - except mine crashed back to the terminal. 

```
panic: HTTP 400 Bad Request, {"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", "captcha_service": "hcaptcha"} [recovered]
	panic: HTTP 400 Bad Request, {"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", "captcha_service": "hcaptcha"}
```

Looks like its some trouble handling the hCaptcha which appears sometimes when you login.

**Comment by ayntgl** [comment]
Try logging in using the official Discord web client using a web browser and solve the captcha that is prompted after clicking on the "Login" button. Once you have done that, log in using your email and password again on Discordo, you should be logged in to your account after that.

If the above-mentioned workaround does not work for you, you can retrieve the authentication token of your account using the web browser's built-in DevTools (Usually, Discord API-related requests headers contain the `Authorization` header which is the authentication token, under "Network" tab and pass the token to the `-token` command line flag to the CLI. Eg: `discordo -token "..."`).
