### ISSUE TITLE
2fa with authenticator app code doesnt work

### ISSUE THREAD

**Issue by qube-03** [ayntgl/discordo#175]
hi,
i was trying to log into discord in discordo because this seemed like a cool project

however, because i try to take precaution, i have 2fa with an authenticator app enabled on my account

upon pressing enter on the authenticator screen, i get this error:

`panic: HTTP 400 Bad Request, {"code": 50035, "errors": {"ticket": {"_errors": [{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}]}}, "message": "Invalid Form Body"} [recovered]
	panic: HTTP 400 Bad Request, {"code": 50035, "errors": {"ticket": {"_errors": [{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}]}}, "message": "Invalid Form Body"}

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
	/home/qube/.local/share/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/application.go:243 +0x4d
panic({0x8bd480, 0xc0004acb40})
	/usr/lib/go/src/runtime/panic.go:884 +0x212
main.main.func1.1.1()
	/home/qube/.cache/paru/clone/discordo-git/src/discordo/main.go:98 +0x218
github.com/rivo/tview.(*Button).InputHandler.func1(0xc000267ac0?, 0x7a001f?)
	/home/qube/.local/share/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/button.go:130 +0x42
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc000128040?, 0xc000013050?)
	/home/qube/.local/share/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/box.go:167 +0x53
github.com/rivo/tview.(*Form).InputHandler.func1(0x40f507?, 0x10?)
	/home/qube/.local/share/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/form.go:673 +0xb7
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc00020a3f0?, 0xc000267be0?)
	/home/qube/.local/share/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/box.go:167 +0x53
github.com/rivo/tview.(*Application).Run(0xc000176460)
	/home/qube/.local/share/go/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/application.go:335 +0x77d
main.main.func1(0xc000128180?)
	/home/qube/.cache/paru/clone/discordo-git/src/discordo/main.go:137 +0x319
github.com/urfave/cli/v2.(*App).RunContext(0xc000102340, {0xa1c5b0?, 0xc00002e1e8}, {0xc000024220, 0x1, 0x1})
	/home/qube/.local/share/go/pkg/mod/github.com/urfave/cli/v2@v2.7.1/app.go:329 +0x9fc
github.com/urfave/cli/v2.(*App).Run(...)
	/home/qube/.local/share/go/pkg/mod/github.com/urfave/cli/v2@v2.7.1/app.go:226
main.main()
	/home/qube/.cache/paru/clone/discordo-git/src/discordo/main.go:140 +0x309`

ive tried with a backup code too, same thing
thanks!

**Comment by qube-03** [comment]
i should add that i can log in perfectly fine with a token

**Comment by ayntgl** [comment]
> i should add that i can log in perfectly fine with a token

This is because of the captcha. See #172 for more information.
