### ISSUE TITLE
[Bug] Server list doesn't update

### ISSUE THREAD

**Issue by fq0e** [ayntgl/discordo#183]
Server list on Discordo:
![edited](https://user-images.githubusercontent.com/90973963/185645877-7d0f4270-43c0-46a1-9f1b-6751c5c9a51d.png)

Server list on Discord:
![edited2](https://user-images.githubusercontent.com/90973963/185645919-1b2b00af-6d47-4520-992c-bb2cfc3e42c2.png)

**Comment by ayntgl** [comment]
Hello @fq0e, thank you for the bug report! Unfortunately, I am unable to reproduce this issue; could you provide reproducible steps so I can take a look into it?

**Comment by fq0e** [comment]
> Hello @fq0e, thank you for the bug report! Unfortunately, I am unable to reproduce this issue; could you provide reproducible steps so I can take a look into it?

I logged in Discordo using the token flag, After that i went into Discord (on Firefox) to join a new server. I restarted my Terminal and the server list wasn't updated

**Comment by ayntgl** [comment]
Close the Firefox tab and try again.

**Comment by Nexuzzzz** [comment]
Not working for me aswell. It displays the friendslists fine but it can't parse the servers. Wouldn't it be easier if you'd dump all errors to a file so users could do some debugging themselves?
