### ISSUE TITLE
Cannot run discordo

### ISSUE THREAD

**Issue by boatinalamp** [ayntgl/discordo#203]
when i run discordo it just exits it. doing nothing
using the aur version, tried building from source to no avail
![image](https://user-images.githubusercontent.com/93244703/187877849-6038df93-255f-4f9d-9037-3aefe087f441.png)

**Comment by ayntgl** [comment]
Can you send the content of the configuration file at `$HOME/.config/discordo/config.lua`?

**Comment by boatinalamp** [comment]
local string = require "string"

-- Whether the mouse is usable or not.
mouse = true

-- The maximum number of messages to fetch and display on the messages panel.
-- Its value must not be lesser than 1 and greater than 100.
messagesLimit = 50

-- Whether to display the timestamp of the message beside the displayed message or not.
timestamps = false

-- The timezone of the timestamps.
-- Learn more: https://pkg.go.dev/time#LoadLocation
timezone = "Local"

-- A textual representation of the time value formatted according to the layout defined by its value.
-- Learn more: https://pkg.go.dev/time#Layout
timeFormat = "3:04PM"

browser = "Chrome"
browserVersion = "104.0.5112.102"
oss = "Linux"

-- Identify properties are connection properties that are dispatched in the IDENTIFY gateway event to trigger the initial handshake with the gateway.
-- Learn more: https://discord.com/developers/docs/topics/gateway#identify
identifyProperties = {
    userAgent = string.format(
        "Mozilla/5.0 (X11; %s x86_64) AppleWebKit/537.36 (KHTML, like Gecko) %s/%s Safari/537.36",
        oss,
        browser,
        browserVersion
    ),
    browser = browser,
    browserVersion = browserVersion,
    os = oss
}

-- Keybindings
keys = {
    application = {
        key(
            "Rune[g]",
            "Focus the guilds tree widget.",
            function(core, event)
                core.Application:SetFocus(core.GuildsTree)
            end
        ),
        key(
            "Rune[c]",
            "Focus the channels tree widget.",
            function(core, event)
                core.Application:SetFocus(core.ChannelsTree)
            end
        ),
        key(
            "Rune[m]",
            "Focus the messages panel widget.",
            function(core, event)
                core.Application:SetFocus(core.MessagesPanel)
            end
        ),
        key(
            "Rune[i]",
            "Focus the message input widget.",
            function(core, event)
                core.Application:SetFocus(core.MessageInput)
            end
        )
    },
    messagesPanel = {
        key(
            "Rune[a]",
            "Open the message actions list widget.",
            function(core, event)
                return openMessageActionsList()
            end
        ),
        key(
            "Up",
            "Select the previous message.",
            function(core, event)
                return selectPreviousMessage()
            end
        ),
        key(
            "Down",
            "Select the next message.",
            function(core, event)
                return selectNextMessage()
            end
        ),
        key(
            "Home",
            "Select the first message.",
            function(core, event)
                return selectFirstMessage()
            end
        ),
        key(
            "End",
            "Select the last message.",
            function(core, event)
                return selectLastMessage()
            end
        )
    },
    messageInput = {
        key(
            "Ctrl+E",
            "Open the external editor.",
            function()
                return openExternalEditor()
            end
        ),
        key(
            "Ctrl+V",
            "Paste the clipboard content.",
            function()
                return pasteClipboardContent()
            end
        )
    }
}

-- Theme
theme = {background = "#1E1E2E", border = "white", title = "white"}

**Comment by boatinalamp** [comment]
also can i make it so that the theme is transperant, so that it shows the terminal colors? sorta like this
![image](https://user-images.githubusercontent.com/93244703/187896433-a3ddf931-57c3-40f6-a15b-8e30920cf2d3.png)
instead of this
![image](https://user-images.githubusercontent.com/93244703/187896490-79253a8b-aba6-4f0a-92ec-d1ad923908bb.png)

**Comment by boatinalamp** [comment]
i fixed it by deleting my config.lua, but what happened to me being able to login to my account with my email and password?
im keeping this open for the above problem, i want it to be transperant

**Comment by ayntgl** [comment]
> i fixed it by deleting my config.lua, but what happened to me being able to login to my account with my email and password? im keeping this open for the above problem, i want it to be transperant

Hey there! Could you tell me which terminal emulator you are using so I can reproduce this issue?

**Comment by boatinalamp** [comment]
im using alacritty.
![image](https://user-images.githubusercontent.com/93244703/188298125-56e6075c-6340-4a5c-8f9c-5439c1cc45f3.png)

**Comment by ayntgl** [comment]
> im using alacritty. ![image](https://user-images.githubusercontent.com/93244703/188298125-56e6075c-6340-4a5c-8f9c-5439c1cc45f3.png)

Please open a new issue for transparency.

**Comment by ayntgl** [comment]
UPDATE: @boatinalamp, Discordo now supports transparency; just set the `theme.background` value to an invalid color name (`"default"`) to use the default terminal color.

**Comment by Si-Ki** [comment]
why are there a million different formats for the config file... at this point I've seen *toml, yml, lua, yoml* , pick one, also, please make a wiki

**Comment by ayntgl** [comment]
> why are there a million different formats for the config file... at this point I've seen _toml, yml, lua, yoml_ , pick one, also, please make a wiki

The first prototype version of Discordo used JSON as a configuration format; later, it was decided that JSON is not suitable as a configuration format due to its restrictiveness, so we switched to TOML. Since Discordo has a lot of configuration fields and nested fields, TOML seemed to be too verbose and cluttered. Considering that, we chose YAML as configuration format for its flexibility and features.

**Comment by Bennse666** [comment]
Hey there,
I am kinda struggling as I seem to have a similar problem as boatinalamp
the difference is.. I don't have a config nor a log file
tried by building it myself with the source and also tried the download
both resulting in the program immediately closing again after start
