### ISSUE TITLE
Compiled under Android ARM64 via Termux Not Running

### ISSUE THREAD

**Issue by defencedog** [ayntgl/discordo#220]
I have compiled & moved binary to `$PREFIX/bin` & it launches perfectly as well. I inserted my token as per this [guideline](https://www.online-tech-tips.com/computer-tips/what-is-a-discord-token-and-how-to-get-one/) 

However after login it just is blank ...altough separators / sections are shown but no messages or channel names?

![Screenshot_20220919_165326_Termux](https://user-images.githubusercontent.com/831749/191011432-49aa7d26-e31e-46f6-9401-c56df7f7c0e4.jpg)

**Comment by ayntgl** [comment]
Hello there, are you using a bot account token to login?

**Comment by defencedog** [comment]
@ayntgl No I have a registered account which i have used, account has been active for over an year now

**Comment by defencedog** [comment]
@ayntgl  any further help you can provide?

**Comment by ayntgl** [comment]
> @ayntgl any further help you can provide?

Unfortunately, I am not able to reproduce this issue. Please join our [Discord server](https://discord.gg/5gecpwkFQ9) so that we can troubleshoot the issue that you are facing.
