### ISSUE TITLE
Auto-login after first time (save token)

### ISSUE THREAD

**Issue by maido** [ayntgl/discordo#246]
Not strictly an issue, but I am not sure how to search for this information so here I am.
It says in the README: "Most of the Discord third-party clients store the token in a configuration file unencrypted. Discordo securely stores the token in the default OS-specific keyring."
But, how do one stores such a token, in a vanilla command line Debian install for instance?
Like, how do I make sure not to have to re-input my login information every time?
Sorry for the relatively noob question, thanks.

**Comment by ayntgl** [comment]
> Not strictly an issue, but I am not sure how to search for this information so here I am. It says in the README: "Most of the Discord third-party clients store the token in a configuration file unencrypted. Discordo securely stores the token in the default OS-specific keyring." But, how do one stores such a token, in a vanilla command line Debian install for instance? Like, how do I make sure not to have to re-input my login information every time? Sorry for the relatively noob question, thanks.

The application automatically saves the token in the default keyring on the first login so you don't have to worry about manually doing it.

**Comment by Si-Ki** [comment]
what? I'm on arch logged in using the token and I have to do it every time, is there some flag in the config to auto login?
