### ISSUE TITLE
Crashing after login

### ISSUE THREAD

**Issue by obnoxiousish** [ayntgl/discordo#43]
discordo                                                                                                                                      127 ↵ o@mary
panic: runtime error: index out of range [-1] [recovered]
        panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
        /home/o/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210909154944-f7430b878d17/application.go:243 +0x4d
panic({0x7901e0, 0xc00118c078})
        /usr/lib/go/src/runtime/panic.go:1038 +0x215
main.onMessagesViewInputCapture(0xc0001c1cb0)
        /home/o/discordo/discordo.go:146 +0x779
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0001fe100, 0xc0001c1cf0)
        /home/o/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210909154944-f7430b878d17/box.go:158 +0x3a
github.com/rivo/tview.(*Flex).InputHandler.func1(0xc0001c1d30, 0x6f4c9f)
        /home/o/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210909154944-f7430b878d17/flex.go:233 +0xd9
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc000268000, 0x10)
        /home/o/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210909154944-f7430b878d17/box.go:161 +0x53
github.com/rivo/tview.(*Flex).InputHandler.func1(0x40e9c7, 0x10)
        /home/o/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210909154944-f7430b878d17/flex.go:233 +0xd9
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc000268090, 0xc0001c1e38)
        /home/o/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210909154944-f7430b878d17/box.go:161 +0x53
github.com/rivo/tview.(*Application).Run(0xc000264000)
        /home/o/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210909154944-f7430b878d17/application.go:335 +0x886
main.main()
        /home/o/discordo/discordo.go:76 +0x431

**Comment by ayntgl** [comment]
#44 should fix this bug
