### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by TheScreechingBagel** [ayntgl/discordo#56]
There should be some sort of docs or at the very least a short guide on  how to use the app without mouse

**Comment by TheScreechingBagel** [comment]
I found keybindings in the config, but that should at least be added to the readme

**Comment by ayntgl** [comment]
> There should be some sort of docs or at the very least a short guide on how to use the app without mouse

Mouse functionality is enabled by default, you can disable it by setting the `Mouse` field in the configuration file to `false`. It has always been on my roadmap to document the entire configuration, that being said, PRs are always welcome.

**Comment by TheScreechingBagel** [comment]
Could you please explain what those (i assume to be) color codes are in the config file? couldn't find anything on that

**Comment by ayntgl** [comment]
> Could you please explain what those (i assume to be) color codes are in the config file? couldn't find anything on that

In `tcell` (dependency of `tview`), all colors are represented by single integer values. The `Color` type is an alias for `uint` type. The low numeric values are the same as used by ECMA-48, and beyond that XTerm. Each color value is a 24-bit integer RGB value for colors. It implements and provides some utility functions to transform hex and RGB color values to 24-bit integer RGB values. Support for hex colors has been on my roadmap for quite some time, do you mind opening an issue?
