### ISSUE TITLE
Captcha panic on login

### ISSUE THREAD

**Issue by iguinea** [ayntgl/discordo#92]
Hi, I am trying to make it run for the first time, and after entering my email + password i get the following panic:

> ./discordo                                                                                                                                                   
panic: HTTP 400 Bad Request, {"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", "captcha_service": "hcaptcha"} [recovered]
	panic: HTTP 400 Bad Request, {"captcha_key": ["captcha-required"], "captcha_sitekey": "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", "captcha_service": "hcaptcha"}

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/application.go:243 +0x4d
panic({0x76b000, 0xc0004f8180})
	runtime/panic.go:1038 +0x215
main.onLoginFormLoginButtonSelected()
	github.com/ayntgl/discordo/main.go:92 +0x3a5
github.com/rivo/tview.(*Button).InputHandler.func1(0xc0001d9cb0, 0x6f0e1f)
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/button.go:129 +0x42
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc000156a80, 0xc0000fe750)
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/box.go:161 +0x53
github.com/rivo/tview.(*Form).InputHandler.func1(0x40ea47, 0x10)
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/form.go:673 +0xb7
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0001fa240, 0xc0001d9dd0)
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/box.go:161 +0x53
github.com/rivo/tview.(*Application).Run(0xc0001f8000)
	github.com/rivo/tview@v0.0.0-20211029090357-1d641bd56588/application.go:335 +0x886
main.main()
	github.com/ayntgl/discordo/main.go:76 +0x967

OS Details: Ubuntu 21.10

Regards

**Comment by ayntgl** [comment]
@iguinea #83
